version: 2.1
jobs:
  pytest:
    docker:
      - image: cimg/python:3.10.1
    resource_class: small 
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
            mkdir test-reports
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 -m pytest | tee test-reports/pytest.log
      - store_artifacts:
          path: test-reports/
          destination: python_app

  makefile:
    docker:
      - image: cimg/python:3.10.1
    resource_class: small 
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            if [ -f Makefile ] ; then make -f Makefile tests ; else echo "No Makefile" ; fi
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
            mkdir test-reports
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 -m pytest | tee test-reports/pytest.log
      - store_artifacts:
          path: test-reports/
          destination: python_app

#  submodule:
#    docker:
#      - image: cimg/python:3.10.1
#    steps:
#      - checkout
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#      - run:
#          command: |
#            python3 -m venv venv
#            . venv/bin/activate
#            pip install -r requirements.txt
#            pip install pytest
#            git submodule update --init 
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#          paths:
#            - "venv"
#      - run:
#          name: Running tests
#          command: |
#            . venv/bin/activate
#            python3 -m pytest | tee test-reports/pytest.log
#      - store_artifacts:
#          path: test-reports/
#          destination: python_app
workflows:
  version: 2
  workflow:
    jobs:
#    - build
    - makefile 
    - pytest
#    - submodule
  
